### PR TITLE
DEPENDENCY: update to lodash 4.17.10

### PR DESCRIPTION
**Pull request by toranb**
Any chance this repo is still maintained? Working thru a list of npm audits and could really use a lodash bump if you've got the bandwidth :)

### CODE REVIEW

**Comment by toranb** [comment]
I'm not familiar w/ your mocha test setup that seems busted on travis -any help getting this back to green?

**Comment by Apollon77** [comment]
would be great to get this merged

**Comment by ntwb** [comment]
@outaTiME Any chance you could merge and release this please?

**Comment by joaogarin** [comment]
yeah this would be great to be merged! cc @outaTiME

**Comment by Mike-Neto** [comment]
Let's get this running @outaTiME !

**Comment by astr0junk** [comment]
merge it please!

**Comment by stevemeisner** [comment]
At this point it should be version `>=4.17.12` 🤔

@outaTiME 👋🏻 😄 

Screen Shot 2019-07-30 at 2 43 15 PM

**Comment by SergeAstapov** [comment]
Giving it another bump

**Pull request closed without merging**
